---
title: "Linear Model Benchmarking"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Linear Model Benchmarking}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo = FALSE}
library(tidyecon)
library(microbenchmark)
suppressPackageStartupMessages(library(dplyr))
library(ggplot2)
library(ezplot)
library(forcats)

```

## Small data set

```{r data setup}
df = mtcars
model_spec = data.frame(expr = c("1", "cyl", "hp", "disp"),
                        stringsAsFactors = FALSE)

options = list(y = "mpg")

x = as.matrix(cbind(intercept = 1, df[c("cyl", "hp", "disp")]))
y = df[["mpg"]]
w = rep(1, nrow(x))

```

## Estimation

```{r run benchmarking}

bm = microbenchmark(
  `estimate(...)` = estimate(df, model_spec, options),
  lm_fit(x, y),
  lm_fit(x, y, w),
  lm.fit(x, y),
  lm.wfit(x, y, w),
  times = 100
)

```

## Results
```{r chart, fig.height = 2, fig.width = 7, echo = FALSE}
bm$expr = fct_reorder(bm$expr, bm$time) %>% fct_rev()

ggplot(bm) +
  geom_boxplot(aes(x = expr, 
                   y = time / 1e6, 
                   group = expr)) +
  scale_y_log10("time (milliseconds)",
                labels = ez_labels) +
  coord_flip() +
  theme_ez(10)
```

